//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Lucene.Net.Util;

namespace AutoComplete.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int WORD_POS {
            get {
                return ((int)(this["WORD_POS"]));
            }
            set {
                this["WORD_POS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public int FREQ_POS {
            get {
                return ((int)(this["FREQ_POS"]));
            }
            set {
                this["FREQ_POS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Word")]
        public string WORD_FIELD_NAME {
            get {
                return ((string)(this["WORD_FIELD_NAME"]));
            }
            set {
                this["WORD_FIELD_NAME"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Frequency")]
        public string FREQ_FIELD_NAME {
            get {
                return ((string)(this["FREQ_FIELD_NAME"]));
            }
            set {
                this["FREQ_FIELD_NAME"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("LUCENE_30")]
        public Version LUCENE_VERSION {
            get {
                return ((Version)(this["LUCENE_VERSION"]));
            }
            set {
                this["LUCENE_VERSION"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("lucene_index")]
        public string LUCENE_INDEX_DIRECTORY {
            get {
                return ((string)(this["LUCENE_INDEX_DIRECTORY"]));
            }
            set {
                this["LUCENE_INDEX_DIRECTORY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("test.in")]
        public string DICTIONARY_FILE_NAME {
            get {
                return ((string)(this["DICTIONARY_FILE_NAME"]));
            }
            set {
                this["DICTIONARY_FILE_NAME"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int HITS_LIMIT {
            get {
                return ((int)(this["HITS_LIMIT"]));
            }
            set {
                this["HITS_LIMIT"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("4")]
        public int LUCENE_INTEGER_TYPE {
            get {
                return ((int)(this["LUCENE_INTEGER_TYPE"]));
            }
            set {
                this["LUCENE_INTEGER_TYPE"] = value;
            }
        }
    }
}
