//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoComplete.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WORD_POS {
            get {
                return ((int)(this["WORD_POS"]));
            }
            set {
                this["WORD_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FREQ_POS {
            get {
                return ((int)(this["FREQ_POS"]));
            }
            set {
                this["FREQ_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Word")]
        public string WORD_FIELD_NAME {
            get {
                return ((string)(this["WORD_FIELD_NAME"]));
            }
            set {
                this["WORD_FIELD_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frequency")]
        public string FREQ_FIELD_NAME {
            get {
                return ((string)(this["FREQ_FIELD_NAME"]));
            }
            set {
                this["FREQ_FIELD_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LUCENE_30")]
        public global::Lucene.Net.Util.Version LUCENE_VERSION {
            get {
                return ((global::Lucene.Net.Util.Version)(this["LUCENE_VERSION"]));
            }
            set {
                this["LUCENE_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lucene_index")]
        public string LUCENE_INDEX_DIRECTORY {
            get {
                return ((string)(this["LUCENE_INDEX_DIRECTORY"]));
            }
            set {
                this["LUCENE_INDEX_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test.in")]
        public string DICTIONARY_FILE_NAME {
            get {
                return ((string)(this["DICTIONARY_FILE_NAME"]));
            }
            set {
                this["DICTIONARY_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int HITS_LIMIT {
            get {
                return ((int)(this["HITS_LIMIT"]));
            }
            set {
                this["HITS_LIMIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int LUCENE_INTEGER_TYPE {
            get {
                return ((int)(this["LUCENE_INTEGER_TYPE"]));
            }
            set {
                this["LUCENE_INTEGER_TYPE"] = value;
            }
        }
    }
}
